TEST_GLOBAL_CONFIG = {
    "MESSAGE_MAX_LENGTH": 1000,
    "TOOLS_DIRECTORY_PAGE_SIZE": 20,
    "SHEDS_DIRECTORY_PAGE_SIZE": 20,
    "USERS_DIRECTORY_PAGE_SIZE": 20,
}

TEST_MESSAGE_MAX_LENGTH = TEST_GLOBAL_CONFIG["MESSAGE_MAX_LENGTH"]
TEST_TOOLS_DIRECTORY_PAGE_SIZE = TEST_GLOBAL_CONFIG["TOOLS_DIRECTORY_PAGE_SIZE"]
TEST_SHEDS_DIRECTORY_PAGE_SIZE = TEST_GLOBAL_CONFIG["SHEDS_DIRECTORY_PAGE_SIZE"]
TEST_USERS_DIRECTORY_PAGE_SIZE = TEST_GLOBAL_CONFIG["USERS_DIRECTORY_PAGE_SIZE"]
